### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by Frano356** [Kingal1337/YugiohProxyMaker#2]
i keep getting this error
![error withprpoxy](https://user-images.githubusercontent.com/71207482/93017252-cfc9eb80-f5f9-11ea-949f-6c13502813f8.png)

**Comment by Kingal1337** [comment]
Is it possible for you to send me your .ydk file?

**Comment by Frano356** [comment]
my apologies but after tinkering with it for a while it works like a charm. I think there was a space somewhere in the file name that caused the initial error. thanks for this awesome program!!

**Comment by Kingal1337** [comment]
good job at finding the problem, and I am glad that you enjoy the program!   :D
