### ISSUE TITLE
Missing proxy cards

### ISSUE THREAD

**Issue by ZenithDoom** [Kingal1337/YugiohProxyMaker#5]
I'm trying to print some Evil Eye card, but the proxy generator can't find them.
How is possible to add them in txt format?

**Comment by Kingal1337** [comment]
could you send me the deck list you are trying to print?

**Comment by ZenithDoom** [comment]
this is the deck as saved in .ydk

#main
20292186
34267821
34267821
82466274
82466274
82466274
18551923
18551923
10802916
10802916
10802916
45955628
45955628
45955628
81344637
81344637
81344637
1475311
1475311
7610394
7610394
7610394
17616743
17616743
17616743
73628505
81439174
83764718
43011492
43011492
79400597
79400597
28957126
28957126
28957126
44133040
44133040
70122149
70122149
70122149
79383919
79383919
#extra
31320433
62709239
84401683
78156759
29479265
85289965
17739335
17739335
38342335
2857636
29357687
29357687
29357687
75452921
71384012
!side
18144506
15693423
15693423
15693423
53334471
53334471
53334471
90846359
90846359
90846359

**Comment by Kingal1337** [comment]
The issue should be fixed in version 1.4.0
