### ISSUE TITLE
Missing proxy cards

### ISSUE THREAD

**Issue by Kakugo1976** [Kingal1337/YugiohProxyMaker#6]
I have an issue with the print of this deck:

#main
14799437
23440231
88301393
51316684
72270339
96055137
25811989
89423971
60228941
60228941
60228941
52038272
52038272
26034577
58446973
58446973
58446973
60551528
1845204
98696958
98696958
98696958
100301099
100301099
100301099
65956182
80845034
80845034
80845034
31444249
31444249
31444249
78748366
78748366
78748366
100301100
100301100
34822850
31548814
38511382
#extra
82734805
82734805
80532587
100301097
100301097
93039339
9940036
100301098
100301098
38342335
2857636
29301450
75452921
71607202
41999284
!side
14799437
23440231
100301097
100200243
66403530
8437145
65956182
7337976
100301100
34822850
61965407
94432298

The program doesn't find the new infernoid cards, even if they are present in the wiki

**Comment by Kingal1337** [comment]
can you give me the names of these cards and a link to the wiki. I am looking for them manually and I cannot find them. I also tried looking for them in dueling book, no success.

edit: also please provide the link on where you made your ydk file

**Comment by Kakugo1976** [comment]
Infernoid Evil - https://yugioh.fandom.com/wiki/Infernoid_Evil
Infernoid Flood - https://yugioh.fandom.com/wiki/Infernoid_Flood
Void Blaze-Up - https://yugioh.fandom.com/wiki/Void_Blaze-Up?so=search
Void Barrier - https://yugioh.fandom.com/wiki/Void_Barrier

My decks are saved as follow:
C:\ProjectIgnis\deck

**Comment by Kingal1337** [comment]
did you use a website to create the YDK file?

**Comment by Kakugo1976** [comment]
No, edopro

**Comment by Kingal1337** [comment]
The reason why the program can't find the cards is because the yugioh wiki doesn't have the password of the card yet and the program looks up the card using this password.  I don't know how EDOPro does it, but I think they have some temporary password which doesn't work with the wiki. When the cards are finally released the program should be able to find them.
